name: Chaos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Print cluster information
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -n kube-system
          helm version
          kubectl version

      - uses: actions/checkout@v2
      
      - name: Deploy an application
        run: |
          kubectl apply -f https://raw.githubusercontent.com/chaos-mesh/apps/master/ping/busybox-statefulset.yaml && sleep 4 && kubectl get all -n busybox

  
      - name: Run chaos mesh action
        uses: chaos-mesh/chaos-mesh-action@master
        env:
          CFG_BASE64: YXBpVmVyc2lvbjogYXBpZXh0ZW5zaW9ucy5rOHMuaW8vdjEKa2luZDogQ3VzdG9tUmVzb3VyY2VEZWZpbml0aW9uCm1ldGFkYXRhOgogIG5hbWU6IG5ldHdvcmtjaGFvcy5jaGFvcy1tZXNoLm9yZwpzcGVjOgogIGdyb3VwOiBjaGFvcy1tZXNoLm9yZwogIG5hbWVzOgogICAga2luZDogTmV0d29ya0NoYW9zCiAgICBsaXN0S2luZDogTmV0d29ya0NoYW9zTGlzdAogICAgcGx1cmFsOiBuZXR3b3JrY2hhb3MKICAgIHNpbmd1bGFyOiBuZXR3b3JrY2hhb3MKICBzY29wZTogTmFtZXNwYWNlZAogIHZlcnNpb25zOgogIC0gbmFtZTogdjFhbHBoYTEKICAgIHNlcnZlZDogdHJ1ZQogICAgc3RvcmFnZTogdHJ1ZQogIHZhbGlkYXRpb246CiAgICBvcGVuQVBJVjNTY2hlbWE6CiAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgYXBpVmVyc2lvbjoKICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIGtpbmQ6CiAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICBtZXRhZGF0YToKICAgICAgICAgICRyZWY6ICcjL2RlZmluaXRpb25zL2lvLms4cy5hcGltYWNoaW5lcnkucGtnLmFwaXMubWV0YS52MS5PYmplY3RNZXRhJwogICAgICAgIHNwZWM6CiAgICAgICAgICAkcmVmOiAnIy9kZWZpbml0aW9ucy9naXRodWIuY29tLmNoYW9zLW1lc2gucGtnLmFwaXMubmV0d29ya2NoYW9zLnYxYWxwaGExLk5ldHdvcmtDaGFvc1NwZWMnCiAgICAgICAgc3RhdHVzOgogICAgICAgICAgJHJlZjogJyMvZGVmaW5pdGlvbnMvZ2l0aHViLmNvbS5jaGFvcy1tZXNoLnBrZy5hcGlzLm5ldHdvcmtjaGFvcy52MWFscGhhMS5OZXR3b3JrQ2hhb3NTdGF0dXMnCiAgdmVyc2lvbnM6CiAgLSBhZGRpdGlvbmFsUHJpbnRlckNvbHVtbnM6CiAgICAtIEpTT05QYXRoOiAubWV0YWRhdGEuY3JlYXRpb25UaW1lc3RhbXAKICAgICAgbmFtZTogQWdlCiAgICAgIHR5cGU6IGRhdGUKICAgIG5hbWU6IHYxYWxwaGExCiAgICBzY2hlbWE6CiAgICAgIG9wZW5BUElWM1NjaGVtYToKICAgICAgICBkZXNjcmlwdGlvbjogTmV0d29ya0NoYW9zIGlzIHRoZSBTY2hlbWEgZm9yIHRoZSBuZXR3b3JrY2hhb3MgQVBJCiAgICAgICAgcHJvcGVydGllczoKICAgICAgICAgIGFwaVZlcnNpb246CiAgICAgICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgICAga2luZDoKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICBtZXRhZGF0YToKICAgICAgICAgICAgJHJlZjogJyMvZGVmaW5pdGlvbnMvaW8uazhzLmFwaW1hY2hpbmVyeS5wa2cuYXBpcy5tZXRhLnYxLk9iamVjdE1ldGEnCiAgICAgICAgICBzcGVjOgogICAgICAgICAgICAkcmVmOiAnIy9kZWZpbml0aW9ucy9naXRodWIuY29tLmNoYW9zLW1lc2gucGtnLmFwaXMubmV0d29ya2NoYW9zLnYxYWxwaGExLk5ldHdvcmtDaGFvc1NwZWMnCiAgICAgICAgICBzdGF0dXM6CiAgICAgICAgICAgICRyZWY6ICcjL2RlZmluaXRpb25zL2dpdGh1Yi5jb20uY2hhb3MtbWVzaC5wa2cuYXBpcy5uZXR3b3JrY2hhb3MudjFhbHBoYTEuTmV0d29ya0NoYW9zU3RhdHVzJwoKLS0tCgphcGlWZXJzaW9uOiBjaGFvcy1tZXNoLm9yZy92MWFscGhhMQpraW5kOiBOZXR3b3JrQ2hhb3MKbWV0YWRhdGE6CiAgbmFtZTogbmV0d29yay1kZWxheQogIG5hbWVzcGFjZTogYnVzeWJveApzcGVjOgogIGFjdGlvbjogZGVsYXkgIyB0aGUgc3BlY2lmaWMgY2hhb3MgYWN0aW9uIHRvIGluamVjdAogIG1vZGU6IGFsbAogIHNlbGVjdG9yOgogICAgcG9kczoKICAgICAgYnVzeWJveDoKICAgICAgICAtIGJ1c3lib3gtMAogIGRlbGF5OgogICAgbGF0ZW5jeTogJzEwbXMnCiAgZHVyYXRpb246ICc1cycKICBzY2hlZHVsZXI6CiAgICBjcm9uOiAnQGV2ZXJ5IDEwcycKICBkaXJlY3Rpb246IHRvCiAgdGFyZ2V0OgogICAgc2VsZWN0b3I6CiAgICAgIHBvZHM6CiAgICAgICAgYnVzeWJveDoKICAgICAgICAgIC0gYnVzeWJveC0xCiAgICBtb2RlOiBhbGw=
          CHAOS_MESH_VERSION: v1.0.0 
